# Generated by Django 5.2.7 on 2025-10-31 17:55

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plagiarism_score', models.FloatField(blank=True, null=True)),
                ('grammar_issues', models.IntegerField(blank=True, null=True)),
                ('citations_missing', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('student', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='thesis_submissions',
                    to=settings.AUTH_USER_MODEL
                )),    
            ],
        ),
    ]
