# Generated by Django 5.2.7 on 2025-10-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plagiarism_score', models.FloatField(blank=True, null=True)),
                ('grammar_issues', models.IntegerField(blank=True, null=True)),
                ('citations_missing', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
            ],
        ),
    ]
