import React, { useState } from "react";
import { useTheme } from "../context/ThemeContext";

const CheckAI = () => {
  const { colors } = useTheme();
  const [text, setText] = useState("");

  return (
    <div
      style={{
        backgroundColor: colors.pageBg,
        minHeight: "100vh",
        padding: "40px 20px",
        boxSizing: "border-box",
        color: colors.text,
      }}
    >
      <div
        style={{
          maxWidth: "900px",
          margin: "0 auto",
        }}
      >
        <h1 style={{ fontSize: "32px", marginBottom: "10px" }}>AI Detection</h1>

        <p style={{ opacity: 0.8, marginBottom: "40px" }}>
          Detect whether parts of your thesis were generated by AI systems.
        </p>

        {/* TEXT INPUT */}
        <textarea
          placeholder="Paste your thesis text for AI analysis..."
          value={text}
          onChange={(e) => setText(e.target.value)}
          style={{
            width: "100%",
            minHeight: "200px",
            padding: "16px",
            borderRadius: "12px",
            border: `1px solid ${colors.text}40`,
            backgroundColor: colors.cardBg,
            color: colors.text,
            fontSize: "16px",
            resize: "vertical",
            marginBottom: "20px",
          }}
        />

        {/* RUN BUTTON */}
        <button
          style={{
            backgroundColor: "#ffbf24",
            color: "#1a1a1a",
            padding: "12px 32px",
            fontSize: "16px",
            borderRadius: "12px",
            border: "none",
            cursor: "pointer",
            fontWeight: 600,
          }}
        >
          Run AI Detection
        </button>
      </div>
    </div>
  );
};

export default CheckAI;
